### ISSUE TITLE
Zookeeper cannot create /es

### ISSUE THREAD

**Issue by a-nldisr** [mesos/elasticsearch#286]
With docker container from hub.docker.com tag 0.3.3 i get: 
ZooKeeperClientException: Cannot create node at /es
KeeperException$NoNodeException: KeeperErrorCode = NoNode for /es

In /mesos i found es (/mesos/es), i do not know if it is supposed to be here. 
This is only when the --zookeeperFrameworkUrl is set (set to same zookeeper instance but with other path). 
When --zookeeperFrameworkUrl is not set there are no issues.

**Comment by frankscholten** [comment]
You mean you can't connect the framework to Zookeeper 3.3? The framework depends on Zookeeper version 3.4.6.

**Comment by a-nldisr** [comment]
Hi, no when using container version 0.3.3

**Comment by frankscholten** [comment]
Could you paste the Marathon JSON command?

**Comment by a-nldisr** [comment]
{
  "id": "elasticsearch",
  "container": {
    "docker": {
      "image": "mesos/elasticsearch-scheduler:0.3.3",
      "forcePullImage": true,
      "network": "HOST"
    }
  },
  "args": ["--elasticsearchNodes", "5", "--elasticsearchClusterName", "padawan", "--zookeeperMesosUrl", "zk://mm01:2181,mm02:2181,mm03:2181/mesos", "--frameworkName", "padawan", "--elasticsearchCpu", "4", "--elasticsearchRam", "65536", "--executorForcePullImage", "true", "--elasticsearchDisk", "204800", "--executorName", "Padawan", "--zookeeperFrameworkUrl", "zk://mm01:2181,mm02:2181,mm03:2181/padawan" ],
  "cpus": 1,
  "mem": 1024.0,
  "env": {
    "JAVA_OPTS": "-Xms128m -Xmx256m"
  },
  "instances": 1
}

Current installed versions: 
Marathon 0.10.0
Mesos 0.23.0
Zookeeper: 3.4.6-0.1

Without  "--zookeeperFrameworkUrl", "zk://mm01:2181,mm02:2181,mm03:2181/padawan" the executors come up. 

With above flag enabled the executors respawn with:
com.sonian.elasticsearch.zookeeper.client.ZooKeeperClientException: Cannot create node at /es
	at com.sonian.elasticsearch.zookeeper.client.ZooKeeperClientService.createPersistentNode(ZooKeeperClientService.java:142)
	at com.sonian.elasticsearch.zookeeper.client.ZooKeeperClientService.doStart(ZooKeeperClientService.java:92)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:85)
	at com.sonian.elasticsearch.zookeeper.settings.ZooKeeperSettingsManager.doStart(ZooKeeperSettingsManager.java:62)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:85)
	at com.sonian.elasticsearch.zookeeper.settings.ZooKeeperSettingsManager.loadZooKeeperSettings(ZooKeeperSettingsManager.java:85)
	at com.sonian.elasticsearch.plugin.zookeeper.ZooKeeperPlugin.additionalSettings(ZooKeeperPlugin.java:47)
	at org.elasticsearch.plugins.PluginsService.updatedSettings(PluginsService.java:214)
	at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:158)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
	at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:166)
	at org.apache.mesos.elasticsearch.executor.elasticsearch.ElasticsearchLauncher.launch(ElasticsearchLauncher.java:22)
	at org.apache.mesos.elasticsearch.executor.mesos.ElasticsearchExecutor.launchTask(ElasticsearchExecutor.java:93)
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /es
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783)
	at com.sonian.elasticsearch.zookeeper.client.ZooKeeperClientService$2.call(ZooKeeperClientService.java:131)
	at com.sonian.elasticsearch.zookeeper.client.ZooKeeperClientService.zooKeeperCall(ZooKeeperClientService.java:574)
	at com.sonian.elasticsearch.zookeeper.client.ZooKeeperClientService.createPersistentNode(ZooKeeperClientService.java:122)

**Comment by frankscholten** [comment]
Thanks we will have a look

**Comment by frankscholten** [comment]
Fix is merged https://github.com/mesos/elasticsearch/pull/291 and snapshot images are built. Please run a second small cluster using the latest image to test it out.

**Comment by a-nldisr** [comment]
wow, quick response. :+1:  Sorry for late reply.
I tested with latest and with 0.4.0 (instead of the earlier 0.3.3  docker image) tested from the official docker registry. Issue is still present, exact same error.

**Comment by frankscholten** [comment]
Yes, this is fixed in the snapshot build. Not in 0.4.0

**Comment by frankscholten** [comment]
build it

**Comment by frankscholten** [comment]
jenkins-build-pr

**Comment by a-nldisr** [comment]
Tested, and fixed. :+1:
